apiVersion: kibana.k8s.elastic.co/v1 
kind: Kibana 
metadata: 
  name: quickstart 
spec: 
  version: 7.7.0 #Make sure Kibana and Elasticsearch are on the same version. 
  http: 
    service: 
      spec: 
        type: LoadBalancer #Adds a External IP 
    tls:
      certificate:
        secretName: elk-secret
  count: 1 
  elasticsearchRef: 
    name: quickstart
